[package]
name = "iam-eks-user-mapper"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
humantime = "2.1.0"
serde = "1.0.197"
serde_yaml = "0.9.25"
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
thiserror = "1.0.58"

# Kubernetes
kube = { version = "0.88.1", features = ["runtime", "derive", "ws"] }
k8s-openapi = { version = "0.21.1", default-features = false, features = [
    "v1_28",
] }

# AWS
aws-config = "1.1.9"
aws-sdk-iam = "1.18.0"
aws-sdk-sts = "1.18.0"
