[package]
name = "iam-eks-user-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["derive", "env"] }
humantime = "2.1.0"
serde = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = "0.7.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
thiserror = "1.0"

# Kubernetes
kube = { version = "0.84.0", features = ["runtime", "derive", "ws"] }
k8s-openapi = { version = "0.18.0", default-features = false, features = ["v1_24", "api"] }

# AWS
aws-config = "0.55.3"
aws-sdk-iam = "0.28.0"
aws-sdk-sts = "0.28.0"
