name: lint commits
on: [pull_request]

permissions:
  contents: read

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  committed:
    name: lint commits
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: lint commits
      uses: crate-ci/committed@master
